# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      #       - ./insert_user.js:/docker-entrypoint-initdb.d/insert_user.js
      - type: bind
        source: /
        target: /
    networks:
      - backend-net
    ports:
      - 27017:27017

  backend:
    image: shubhanshi/backend
    ports:
      - 9192:9192
    networks:
      - backend-net
    depends_on:
      - mongodb

  frontend:
    image: shubhanshi/frontend
    networks:
      - backend-net
    ports:
      - 3000:3000

networks:
  backend-net: